cmake_minimum_required(VERSION 3.20)

if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
set (CMAKE_PREFIX_PATH "C:/Qt/5.15.2/mingw81_64")# why???
endif()

find_package(QT NAMES Qt6 Qt5 Core)

set(DIR_NAME
    "Qt${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}_${CMAKE_CXX_COMPILER_ID}_${CMAKE_BUILD_TYPE}"
)

if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "8")
    set(DIR_NAME "${DIR_NAME}_x64")
else()
    set(DIR_NAME "${DIR_NAME}_x32")
endif()

set(OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/${DIR_NAME}/bin")

set(PLUGINS_DIR "${OUTPUT_DIRECTORY}/plugins")

set(STATIC_LIBS_DIR "${CMAKE_SOURCE_DIR}/bin/${DIR_NAME}/static_libs")

message(${PROJECT_NAME})
message("CMAKE_SOURCE_DIR >> ${CMAKE_SOURCE_DIR}")
message("STATIC_LIBS_DIR  >> ${STATIC_LIBS_DIR}")
message("PLUGINS_DIR      >> ${PLUGINS_DIR}")
message("DIR_NAME         >> ${DIR_NAME}")

link_directories(STATIC_LIBS_DIR)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PLUGINS_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${STATIC_LIBS_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PLUGINS_DIR})


